FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get --no-install-recommends -y install python siege \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists 
ADD gen_url_list.py /tmp/
ADD client.sh /
ENTRYPOINT ["/client.sh"]
