curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/foo
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
curl localhost/bar
sleep 0.3
